# UMR ENTROPIE WEBSITE
entropieadb:
  hostname: entropieadb
  image: sylviefiat/alpine-mysql
  volumes:
    - ./entropieadb_data:/var/lib/mysql
  ports:
    - "3308:3306"
  environment:
    - MYSQL_USER=docker
    - MYSQL_USER_PWD=docker
    - MYSQL_ROOT_PWD=docker

entropie:
  hostname: entropie
  image: sylviefiat/docker-concrete5.7
  ports:
    - "81:80"
    - "24:25"
  environment:
    - DB_USER=root
    - DB_PASS=docker
    - DB_HOST=mysql
    - DB_NAME=concrete
  volumes:
    - ./entropie_data/application:/app/application
    - ./entropie_data/packages:/app/packages
    - ./entropie_data/updates:/app/updates
    - ./entropie_data/concrete:/app/concrete
  links:
    - entropiedb:entropiedb
    - entropieadb:entropieadb
    - entropiegis:entropiegis

entropiegis:
  hostname: entropiegis
  image: sylviefiat/docker-geoserver
  command: "/opt/geoserver/bin/startup.sh"
  volumes:
    - ./entropiegis_data:/opt/geoserver/data_dir
  ports:
    - "8081:8080"
  links:
    - entropiedb:entropiedb
